/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BottomSheet {
    'closeBottomSheet': () => Promise<void>;
    'openBottomSheet': () => Promise<void>;
  }
  interface CsModal {
    'closeModal': () => Promise<void>;
    'openModal': () => Promise<void>;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SideDrawer {
    'open': boolean;
  }
}

declare global {


  interface HTMLBottomSheetElement extends Components.BottomSheet, HTMLStencilElement {}
  var HTMLBottomSheetElement: {
    prototype: HTMLBottomSheetElement;
    new (): HTMLBottomSheetElement;
  };

  interface HTMLCsModalElement extends Components.CsModal, HTMLStencilElement {}
  var HTMLCsModalElement: {
    prototype: HTMLCsModalElement;
    new (): HTMLCsModalElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {}
  var HTMLSideDrawerElement: {
    prototype: HTMLSideDrawerElement;
    new (): HTMLSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'bottom-sheet': HTMLBottomSheetElement;
    'cs-modal': HTMLCsModalElement;
    'my-component': HTMLMyComponentElement;
    'side-drawer': HTMLSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface BottomSheet extends JSXBase.HTMLAttributes<HTMLBottomSheetElement> {}
  interface CsModal extends JSXBase.HTMLAttributes<HTMLCsModalElement> {}
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SideDrawer extends JSXBase.HTMLAttributes<HTMLSideDrawerElement> {
    'onDrawerClosed'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }

  interface IntrinsicElements {
    'bottom-sheet': BottomSheet;
    'cs-modal': CsModal;
    'my-component': MyComponent;
    'side-drawer': SideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


